version: 0.1

phases:
  build:
    commands:
      - npm install
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - favicon.png
    - Jeff-Diers-resume.pdf
    - styles/main.css
    - Rubrik/*
    - dist/bundle.js